"""initial migration

Revision ID: 470bbe9103c0
Revises: None
Create Date: 2015-12-22 15:07:30.181690

"""

# revision identifiers, used by Alembic.
revision = '470bbe9103c0'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions',
    sa.Column('ques', sa.String(length=1024), nullable=True),
    sa.Column('id', sa.String(length=64), nullable=True),
    sa.Column('quesid', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('quesid')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('passwd', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('questions')
    ### end Alembic commands ###
